### ISSUE TITLE
Error Unhandled Runtime

### ISSUE THREAD

**Issue by KateFoxBeta** [educlopez/educalvolopez.com#3]
Buenas, 
al realizar npm run dev se generan dos errores 

![bc11b1d740f4f77e78147c8e49e9ad2d](https://user-images.githubusercontent.com/55601969/228338485-01a80ee6-f3ea-4963-be40-d92fc5e1c18d.png)

Parece ser que alguna pagina tiene algún tipo de conflicto.

**Comment by educlopez** [comment]
Hola, puede ser que falten cosas en el .env, acabo de dejar el readme actualizado que el otro día quite todo el tema de mostrar el tiempo de la ubicación y agregué una conexión a la api de Github para traer los proyectos pinned de mi cuenta en la página de proyectos. 

Confirmame si te funciona.

**Comment by educlopez** [comment]
Hola el token de github lo puedes generar aquí:
https://github.com/settings/tokens

Lo de spotify si no lo usas puedes quitar el componente y todo lo relacionado

Gracias por el feedback 😃

**Comment by KateFoxBeta** [comment]
Correcto, eliminando spotify y con el token de github ya funciona. Muchas gracias 😄
